package com.example.demo.dto;

import java.util.Date;

public class UserInfoDto {
    private String _id;
    private String account;
    private String address;
    private String actionType;
    private String alias;
    private String associateType;
    private String baseOrgCOde;
    private String birthDay;
    private String bureauCode;
    private String bureauName;
    private String code;
    private Date createTime;
    private String creatorId;
    private String duty;
    private String education ;
    private String email;
    private String employeeId;
    private String employeeIdList;
    private String employeeName;
    private String employeeStatus;
    private String fastQueryValue;
    private String fax;
    private String fixPhone;
    private String fullSpell;
    private String honePhone;
    private String idList;
    private String identityCard;
    private Integer isencryption;
    private Integer islock;
    private Integer jobStatus;
    private Integer lockPassword;
    private String mark;
    private Integer marriage;
    private Date maxCreateTime;
    private Date minCreateTime;
    private String mobilePhone;
    private String modifierId;
    private String nameFullPath;
    private String nationality;
    private String note;
    private String orgCode;
    private String orgId;
    private String orgName;
    private String orgStructureId;
    private Integer pageNo;
    private Integer pageSize;
    private String parentOrgId;
    private String password;
    private String postIdList;
    private Integer postRelationType;
    private String provinceCode;
    private String provinceName;
    private String qq;
    private String sapHROrgId;
    private String sapHRUserId;
    private Integer sex;
    private String shortSpell;
    private String sortFieldName;
    private Integer sortOrder;
    private String sortType;
    private Integer state;
    private String title;
    private Date updateTime;
    private String userId;
    private String userIdList;
    private Integer userState;
    private Integer userType;
    private String zip;

}
